name:       dhall-release-hashes
version:    0.1.0.0
github:     jlavelle/dhall-release-hashes
license:    MIT
author:     John Lavelle
maintainer: jlavelle604@gmail.com
copyright:  2020 John Lavelle

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - aeson
  - aeson-pretty
  - base >=4.13 && <4.14
  - base16
  - bytestring
  - containers
  - cryptohash-sha256
  - foldl
  - github
  - github-asset-fold >=0.5.0.0 && <0.6
  - profunctors
  - text

executables:
  dhall-release-hashes:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
